name: Java CI with Maven

on: [push, pull_request]

# https://github.com/jenkinsci/jenkinsfile-runner-github-actions
jobs:
  jenkinsfile-runner-prepackaged:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jenkinsfile-runner-prepackaged
        uses: jenkinsci/jenkinsfile-runner-github-actions/jenkinsfile-runner-prepackaged@master