name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2204
      - name: Setup Visual Studio Build Tools
        run: sudo apt-get update && sudo apt-get install -y dotnet-sdk-7.0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
          java-package: jdk
          architecture: x64

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -Dmaven.javadoc.skip=true verify --file pom.xml